### ISSUE TITLE
App crash issue: After getting response my app will crash.

### ISSUE THREAD

**Issue by harshitshakya123** [google-pay/react-native-make-payment#2]
import { PaymentRequest as Gpay } from "@google/react-native-make-payment";

  const paymentDetails = {
  total: {
    amount: {
      currency: "USD",
      value: "14.95",
    },
  },
};
const googlePayRequest = {
  apiVersion: 2,
  apiVersionMinor: 0,
  allowedPaymentMethods: [
    {
      type: "CARD",
      parameters: {
        allowedAuthMethods: ["PAN_ONLY", "CRYPTOGRAM_3DS"],
        allowedCardNetworks: ["AMEX", "DISCOVER", "JCB", "MASTERCARD", "VISA"],
      },
      tokenizationSpecification: {
        type: "PAYMENT_GATEWAY",
        parameters: {
          gateway: "stripe",
          "stripe:version": "2018-10-31",
          "stripe:publishableKey":
            "myPublishertestkey",
        },
      },
    },
  ],
  merchantInfo: {
    // merchantId: "01234567890123456789",
    merchantId: "",
    merchantName: "",
  },
  transactionInfo: {
    totalPriceStatus: "FINAL",
    totalPrice: paymentDetails.total.amount.value,
    currencyCode: paymentDetails.total.amount.currency,
    countryCode: "US",
  },
};

  const paymentMethods = [
  {
    supportedMethods: "google_pay",
    data: googlePayRequest,
  },
];
  const GooglePay = new Gpay(paymentMethods, paymentDetails);
  function showPaymentForm() {
    try {
      GooglePay.show()
        .then((response) => {
          if (response === null) {
            console.log("Payment sheet cancelled");
          } else {
            console.log("REsponse", JSON.stringify(response));
          }
        })
        .catch((error) => {
          console.log(`paymentRequest.show() error: ${error}`);
        });
    } catch (err) {
      console.log("final error", err);
    }
  }

**Comment by stephenmcd** [comment]
Can you provide any output from the error?

**Comment by harshal311989** [comment]
Same here I am got crash like below 
 `FATAL EXCEPTION: main
Process: com.katalogmarketplace, PID: 28929
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=991, result=-1, data=Intent { (has extras) }} to activity {com.katalogmarketplace/com.katalog.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6005)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6044)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8779)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
	at com.busfor.RNGooglePayModule.handlePaymentSuccess(RNGooglePayModule.java:185)
	at com.busfor.RNGooglePayModule.-$$Nest$mhandlePaymentSuccess(Unknown Source:0)
	at com.busfor.RNGooglePayModule$1.onActivityResult(RNGooglePayModule.java:60)
	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:375)
	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:822)
	at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:107)
	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:136)
	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
	at android.app.Activity.dispatchActivityResult(Activity.java:8951)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5998)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6044) 
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:226) 
	at android.os.Looper.loop(Looper.java:313) 
	at android.app.ActivityThread.main(ActivityThread.java:8779) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) `

**Comment by dmengelt** [comment]
@harshal311989 are you still able to reproduce this issue?

**Comment by dmengelt** [comment]
No activity. Please re-open if needed
